apiVersion: v1
kind: Namespace
metadata:
  name: secret-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-deployer-service-acc
  namespace: secret-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-deployer-cluster-role
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-deployer-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-deployer-cluster-role
subjects:
- kind: ServiceAccount
  name: secret-deployer-service-acc
  namespace: secret-deployer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-controller
  namespace: secret-deployer
  labels:
    app: custom-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-controller
  template:
    metadata:
      labels:
        app: custom-controller
    spec:
      containers:
        - image: vivekhiwarkar/secret-deployer:0.0.2
          name: secret-deployer-container
      serviceAccountName: secret-deployer-service-acc